SCHEMA_THEN_API = "SCHEMA_THEN_API"
API_ONLY = "API_ONLY"
EXTRACT_SCHEMAS_ONLY = "EXTRACT_SCHEMAS_ONLY"
COMPARE_API_SPECS = "COMPARE_API_SPECS"

ALL_INTENTS = [
    SCHEMA_THEN_API,
    API_ONLY,
    EXTRACT_SCHEMAS_ONLY,
    COMPARE_API_SPECS,
]
